name: magic_master
description: MagicSing control app
version: 1.0.0+4

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  sqflite: ^1.2.0
  mqtt_client: ^5.6.2
  flutter_cache_manager: ^1.1.3
  recase: ^2.0.1
  qr_mobile_vision: 
    git:
      url: https://github.com/yongjhih/flutter_qr_mobile_vision
  shared_preferences: ^0.5.6
  http: ^0.12.0+2
  uuid: ^2.0.4
  cached_network_image: ^2.0.0-rc.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true